name: Fetch Unity License

on: workflow_dispatch

# Go to https://license.unity3d.com/manual to get license
jobs:
  requestManualActivationFile:
    name: Request Manual Activation File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: webbertakken/unity-request-manual-activation-file@v2
        id: getManualLicenseFile

      - uses: actions/upload-artifact@v2
        with:
          name: Manual Activation File
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}